// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aezbtbqqmeuynjkqdxjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlemJ0YnFxbWV1eW5qa3FkeGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NjEwNDEsImV4cCI6MjA4OTIzNzA0MX0.H7ic6Z24xONhJAzdTVXXRIoWc4bBgdcpEZBolz0SVUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});